gui:
  skipDiscardChangeConfirm: false

  # Use nerd fonts for better icons
  nerdFontsVersion: "3"

  showFileTree: true
  sidePanelWidth: 0.3

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
