gui:
  skipDiscardChangeConfirm: false

  # Use nerd fonts for better icons
  nerdFontsVersion: "3"

  showFileTree: true
  sidePanelWidth: 0.3

git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
