# =============================================================================
# HOST FEATURES
# =============================================================================
# setup_gui:          Installs Cinnamon, Brave, PyCharm, Fonts, etc.
# setup_server: Installs UFW, Cockpit, Unattended Upgrades, etc.
# setup_wireguard:    Installs Wireguard package and wg0.conf
# setup_nvidia:       Installs proprietary NVIDIA drivers and tools
# setup_smb_share:    Mounts the specific 'chopin' Samba share
# setup_docker:
# setup_conda:
# =============================================================================

hosts_features:
  rone:
    setup_gui: false
    setup_fonts: false
    setup_server: true
    setup_wireguard: true
    setup_nvidia: false
    setup_smb_share: false
    setup_hd_idle: true
    setup_syncthing: false
    has_bitwarden: true

  fractal:
    setup_gui: true
    setup_fonts: true
    setup_server: false 
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: false
    setup_conda: true
    setup_nfs_share: true
    setup_syncthing: true
    has_bitwarden: true

  morefine:
    setup_gui: true
    setup_fonts: true
    setup_server: false
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: false
    setup_nfs_share: true
    setup_conda: true
    setup_docker: true
    setup_syncthing: true
    has_bitwarden: true

  mintvm:
    setup_gui: true
    setup_fonts: true
    setup_server: false
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: false
    setup_conda: true
    setup_docker: true
    setup_syncthing: true
    has_bitwarden: true
  
  chopin:
    setup_gui: false
    setup_fonts: false
    setup_server: true
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: false
    setup_smb_server: true
    setup_nfs_share: false
    setup_nfs_server: true
    setup_conda: true
    setup_docker: true
    setup_chopin_specific: true
    setup_syncthing: true
    has_bitwarden: true

  vmubuntuserver:
    setup_gui: false
    setup_fonts: false
    setup_server: true
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: false
    setup_smb_server: true
    setup_conda: true
    setup_docker: true
    setup_chopin_specific: true
    setup_syncthing: true
    has_bitwarden: true

  ALFR-CY5VCK3-L:
    setup_gui: false
    setup_fonts: true
    setup_server: false
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: false
    setup_smb_server: false
    setup_conda: true
    setup_docker: true
    setup_syncthing: false
    has_bitwarden: false
    runs_within_wsl: true

local_storage:
  rone:
    drives:
      - uuid: "0cfde01b-f95e-4c53-842b-42674ddd3b25"
        path: "/mnt/wdd"
        owner: "paul"
        filesystem_type: ext4
        options: defaults

  fractal:
    drives:
      - uuid: "bca615bc-2c63-4db8-8408-ddd48b27ab55"
        path: "/mnt/ext4_data"
        owner: "paul"
        filesystem_type: ext4
        options: defaults
        symlink_dirs:
          - "Downloads"
          - "Documents"
          - "Pictures"
          - "Torrents"

  morefine:
    drives:
      - uuid: "bd302b3d-808e-4b51-99e6-65ce3390cf01"
        path: "/mnt/stb"
        owner: "paul"
        filesystem_type: ext4
        options: defaults
        symlink_dirs:
          - "Downloads"
          - "Documents"
          - "Pictures"
          - "Torrents"

  chopin:
    drives:
      - uuid: "03ff35b6-61a0-4b23-8b09-6431e2b71955"
        path: "/mnt/btr"
        owner: "paul"
        filesystem_type: "btrfs"
        options: "defaults,compress=zstd:1,noatime"
