# =============================================================================
# HOST FEATURES
# =============================================================================
# setup_gui:          Installs Cinnamon, Brave, PyCharm, Fonts, etc.
# setup_server_utils: Installs UFW, Cockpit, Unattended Upgrades, etc.
# setup_wireguard:    Installs Wireguard package and wg0.conf
# setup_nvidia:       Installs proprietary NVIDIA drivers and tools
# setup_smb_share:    Mounts the specific 'minis' Samba share
# =============================================================================

hosts_features:
  rone:
    setup_gui: false
    setup_server: true
    setup_wireguard: true
    setup_nvidia: false
    setup_smb_share: false
    setup_hd_idle: true

  fractal:
    setup_gui: true
    setup_server: false 
    setup_wireguard: false
    setup_nvidia: true
    setup_smb_share: false

  minis:
    setup_gui: false
    setup_server: true
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: true

  morefine:
    setup_gui: true
    setup_server: false
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: false

  mintvm:
    setup_gui: true
    setup_server: false
    setup_wireguard: false
    setup_nvidia: false
    setup_smb_share: true

local_storage:
  rone:
    drives:
      - uuid: "0cfde01b-f95e-4c53-842b-42674ddd3b25"
        path: "/mnt/wdd"
        owner: "paul"

  fractal:
    drives:
      - uuid: "bca615bc-2c63-4db8-8408-ddd48b27ab55"
        path: "/mnt/ext4_data"
        owner: "paul"
        symlink_dirs:
          - "Downloads"
          - "Documents"
          - "Pictures"
          - "Torrents"

  minis:
    drives:
      - uuid: "4c1bbb69-68bd-40c9-8257-c519a91d7d99"
        path: "/mnt/mx500_2t"
        owner: "paul"
      - uuid: "134a9171-9aea-4363-809b-5c6565386970"
        path: "/mnt/mx500_4t"
        owner: "paul"
